version: "3"

services:
  failover:
    build:
      context: .
      args:
        - RELEASE_TAG=${RELEASE_TAG}
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./scripts:/scripts
    ports:
      - 8080:9090
